# Generated by Django 3.0.4 on 2020-03-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='reviews',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
