# Generated by Django 3.0.4 on 2020-05-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0004_testimonials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'verbose_name': 'Landing page destination', 'verbose_name_plural': 'Landing page destionations'},
        ),
        migrations.AlterModelOptions(
            name='testimonials',
            options={'verbose_name': 'testimonial', 'verbose_name_plural': 'testimonials'},
        ),
    ]
