# Generated by Django 3.0.4 on 2020-05-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='destionations',
            new_name='destinations',
        ),
    ]
