# Generated by Django 3.0.4 on 2020-05-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_auto_20200513_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinations',
            options={'verbose_name': 'destination', 'verbose_name_plural': 'destinations'},
        ),
        migrations.AddField(
            model_name='destinations',
            name='offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='feature1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='feature2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='feature3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='feature4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='price',
            field=models.IntegerField(blank=True),
        ),
    ]
