from django.shortcuts import render
from .models import subscribers
from Travelwebsite.settings import EMAIL_HOST_USER
from django.core.mail import send_mail
# Create your views here.

def subscribe_details(request):
    if request.method == "POST":
        name = request.POST['name']
        email = request.POST['email']
        user = subscribers(name=name, email = email)
        user.save()
        
        subject="Demo mail by django"
        message="Email is generated by Django"
        #Fuction for sending mail
        send_mail(subject,message,EMAIL_HOST_USER,[email],fail_silently=False)
        return render(request,'subscribe.html')    
