# Generated by Django 3.0.4 on 2020-04-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='name',
            field=models.CharField(default='User', max_length=100),
        ),
    ]
