# Generated by Django 3.0.4 on 2020-05-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_subscribers_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name': 'subscriber', 'verbose_name_plural': 'subscribers'},
        ),
    ]
